INSERT INTO address (                       id,
                                            address_type,
                                            city ,
                                            postal_code,
                                            country,
                                            street,
                                            state,
                                            employee_id,
                                            date_created,
                                            last_updated)
VALUES (10000,
        'permannent',
        'jaipur',
        '0049543',
        'india',
        'BDA',
        'MP',
        10000,
        '2021-09-03 04:30:00',
        '2021-09-03 04:30:00'),
       (10001,
               'permannent',
               'satna',
               '0049543',
               'india',
               'BDA',
               'MP',
               10001,
               '2021-09-03 04:30:00',
               '2021-09-03 04:30:00');
