INSERT INTO bank_account (                                            id ,
                                                                 account_holder_name ,
                                                                 account_number ,
                                                                 account_type ,
                                                                 bank_name ,
                                                                 branch_name,
                                                                 ifsc_code,
                                                                 employee_id ,
                                                                 date_created ,
                                                                 last_updated )
VALUES (10000,
        'Apurv',
        00454444449543,
        'saving',
        'SBI',
        'sainik',
        'SJKSS8',
        10000,
        '2021-09-03 04:30:00',
        '2021-09-03 04:30:00'),
       (       10001,
                'sahil',
                00454444449543,
                 'current',
                'PNB',
                'BDA',
                'SJKSS8',
                10001,
                '2021-09-03 04:30:00',
                '2021-09-03 04:30:00');
